import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import CustomCursor from "../../components/ui/animations/cursormoviment";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body className={`${bebas.variable} antialiased`}>
        <>
          <CustomCursor />
          {children}
        </>
        </body>
        </html>
      </ClerkProvider>
  );
}