import { type Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "../globals.css";
import CustomCursor from "../../../Components/ui/animations/cursor-effect";
import Navbar from "../../../Components/index/Nab";
import { Footer } from "../../../Components/index/Footer";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CustomCursor />
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
